set -g default-shell "$TMUX_DEFAULT_SHELL"
set -g default-command "$TMUX_DEFAULT_SHELL"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
# Inactive pane border
set -g pane-border-style fg=colour238
set -g window-style fg=colour250

# Active pane border
set -g pane-active-border-style fg=colour51,bold
set -g window-active-style fg=default

set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{pane_title}"

