set -g default-command "$TMUX_DEFAULT_SHELL"

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -as terminal-features ",xterm-256color:RGB"
set -sg escape-time 10
set -g focus-events on
# Inactive pane border
set -g pane-border-style fg=colour238
set -g window-style fg=colour250

# Active pane border
set -g pane-active-border-style fg=colour51,bold
set -g window-active-style fg=default

set -g pane-border-status top
set -g pane-border-format "#{pane_index} #{pane_title}"

set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

